<?php
/**
 * Remove a Tag.
 * 
 * @package tagger
 * @subpackage processors
 */
class TaggerTagRemoveProcessor extends modObjectRemoveProcessor {
    public $classKey = 'TaggerTag';
    public $languageTopics = array('tagger:default');
    public $objectType = 'tagger.tag';

    /**
     * @return bool
     *
     * Rimuovo indici corrispondenti al tag
     */
    public function afterRemove()
    {
        $indexTag = $this->modx->getObject('SearchIndexTag',array(
            'tag_id'=>$this->object->id
        ));
        if($indexTag instanceof SearchIndexTag){
            $index = $this->modx->getObject('SearchIndex',$indexTag->index_id);
            if($index) $index->remove();
            $indexTag->remove();
        }
        return parent::afterRemove(); // TODO: Change the autogenerated stub
    }
}
return 'TaggerTagRemoveProcessor';