<?php
/**
 * Remove a Group.
 * 
 * @package tagger
 * @subpackage processors
 */
class TaggerGroupRemoveProcessor extends modObjectRemoveProcessor {
    public $classKey = 'TaggerGroup';
    public $languageTopics = array('tagger:default');
    public $objectType = 'tagger.group';

    /**
     * @return bool
     *
     * Rimuovo indici collegati ai tag
     */
    public function beforeRemove()
    {
        $tags = $this->modx->getCollection('TaggerTag',array(
            'group:='=>$this->object->id
        ));
        foreach($tags as $tagObj){
            // Cerco SearchIndex e SearchIndexTag
            $indexTag = $this->modx->getObject('SearchIndexTag',array(
                'tag_id'=>$tagObj->id
            ));
            if($indexTag instanceof SearchIndexTag){
                $index = $this->modx->getObject('SearchIndex',$indexTag->index_id);
                if($index) $index->remove();
                $indexTag->remove();
            }
        }
        return parent::beforeRemove(); // TODO: Change the autogenerated stub
    }
}
return 'TaggerGroupRemoveProcessor';